#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


int numprocs=-1;
FILE **infd=NULL,  *outfd=NULL;

struct lininf {
    double min;
    double max;
    int    minloc;
    int    maxloc;
};

#define MAXLINE 128

#define TLINE_INIT(_t) { _t.min=9999999999.99; _t.max=0.0; \
       _t.minloc=-1; _t.maxloc=-1;}
#define TLINE_MIN(_t, _time, _i){ \
           if ( _time < _t.min ) { \
	       _t.min    = _time;  \
	       _t.minloc = _i;}}
#define TLINE_MAX(_t, _time, _i) { \
	    if ( _time > _t.max ) { \
		_t.max = _time;     \
		_t.maxloc =_i;}}

void iterations_init (int argc, char ** argv); 

int main (int argc, char **argv )
{
    int i, ret, done=0, no_line,  iter=0;
    char line[MAXLINE], *basestr, reqstr;
    double time;
    struct lininf tline;

    iterations_init ( argc, argv );

    /* Read infile and store the values in the according list */
    while ( !done ) {
	TLINE_INIT(tline);

	for ( i=0; i< numprocs; i++ ) {
	    no_line = 0;
	    while ( !no_line ) {
		ret = fscanf ( infd[i], "%[^\n]\n", line );
		if ( EOF == ret ) {
		    goto exit;
		}
		if ( line[0] == '#' ) {
		    /* Skip comment lines */
		    continue;
		}
		no_line = 1;
	    }	    
	    
	    basestr = strstr ( line, ")" );
	    sscanf ( basestr, "%1s %lf\n", &reqstr, &time );

	    TLINE_MIN(tline,time,i);
	    TLINE_MAX(tline,time,i);
	}

	fprintf (outfd, 
		 "%3d %8.4lf %3d %8.4lf %3d\n", 
		 iter, 
		 tline.min * 1000000, 
		 tline.minloc,
		 tline.max * 1000000, 
		 tline.maxloc );
	iter++;
    }
    
 exit:

    for ( i=0; i< numprocs; i++ ) {
	fclose ( infd[i]);
    }

    fclose ( outfd );
    free ( infd );

    return ( 0 );
}


/**********************************************************************/
/**********************************************************************/
/**********************************************************************/
void iterations_init (int argc, char ** argv ) 
{
    char inname[50];
    int i;


    if (argc < 2 )
    {
	printf(" Usage : iterations <numprocs> <options> \n\n");
	printf("   iterations takes the output files generated by ADCL and \n");
	printf("   determines for each individual measurement the minimal and \n");
	printf("   maximual value across all processes and the according locations\n");
	printf(" Options: \n");
	printf("   <numprocs>   : number of processes \n");
	exit ( 1 ) ;
    }
    
    numprocs    = atoi( argv[1] );
    

    infd = (FILE **) malloc ( numprocs * sizeof(FILE *) );
    if ( NULL == infd ) {
	exit (-1);
    }

    outfd = fopen ("iterations.out", "w");
    if ( NULL == outfd ) {
	exit ( -1 );
    }


    for ( i = 0; i < numprocs; i++ ) {
	sprintf( inname, "%d.out", i);
	infd[i] = fopen ( inname, "r" );
    }	

    return;
}
